// <auto-generated>
// Code generated by LUISGen SillyBeeMortgageAssist.json -cs Luis.SillyBeeLuis -o C:\Users\Administrator\Documents\Code\SillyBeeAssistant\VirtualAssistant
// Tool github: https://github.com/microsoft/botbuilder-tools
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using System.Diagnostics;

namespace VirtualAssistant
{
    public partial class SillyBeeLuis: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            Add_account_or_document, 
            Buy_It, 
            Not_like_it, 
            Happy_with_Finance, 
            Like_It, 
            None, 
            Not_buy_it, 
            Not_happy_with_finance, 
            Snapt_It, 
            Thinking, 
            Utilities_Confirm, 
            Utilities_Escalate, 
            Utilities_Reject
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] Utilities_DirectionalReference;

            // Built-in entities
            public double[] number;

            public double[] ordinal;

            // Instance
            public class _Instance
            {
                public InstanceData[] Utilities_DirectionalReference;
                public InstanceData[] number;
                public InstanceData[] ordinal;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<SillyBeeLuis>(JsonConvert.SerializeObject(result, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore }));
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }

        public Intent TopIntentNoScore()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return maxIntent;
        }
    }
}
